# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.application_area = QtWidgets.QScrollArea(self.tab2)
        self.application_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.application_area.setLineWidth(0)
        self.application_area.setWidgetResizable(True)
        self.application_area.setObjectName("application_area")
        self.application_area_widget = QtWidgets.QWidget()
        self.application_area_widget.setGeometry(QtCore.QRect(0, 0, 774, 357))
        self.application_area_widget.setObjectName("application_area_widget")
        self.application_area_layout = QtWidgets.QVBoxLayout(self.application_area_widget)
        self.application_area_layout.setObjectName("application_area_layout")
        self.application_area.setWidget(self.application_area_widget)
        self.verticalLayout_2.addWidget(self.application_area)
        self.app_divider = QtWidgets.QFrame(self.tab2)
        self.app_divider.setLineWidth(2)
        self.app_divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.app_divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.app_divider.setObjectName("app_divider")
        self.verticalLayout_2.addWidget(self.app_divider)
        self.application_view_panel_2 = QtWidgets.QScrollArea(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.application_view_panel_2.sizePolicy().hasHeightForWidth())
        self.application_view_panel_2.setSizePolicy(sizePolicy)
        self.application_view_panel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.application_view_panel_2.setLineWidth(0)
        self.application_view_panel_2.setWidgetResizable(True)
        self.application_view_panel_2.setObjectName("application_view_panel_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 774, 69))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.application_view_panel_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.application_view_panel_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cyan Manager"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Applications"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
