# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_expansionWin(object):
    def setupUi(self, expansionWin):
        expansionWin.setObjectName("expansionWin")
        expansionWin.resize(558, 575)
        self.verticalLayout = QtWidgets.QVBoxLayout(expansionWin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(expansionWin)
        self.tabWidget.setMinimumSize(QtCore.QSize(540, 500))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_queries = QtWidgets.QWidget()
        self.tab_queries.setObjectName("tab_queries")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_queries)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.queryList = QtWidgets.QListWidget(self.tab_queries)
        self.queryList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.queryList.setObjectName("queryList")
        self.verticalLayout_2.addWidget(self.queryList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deleteQuery = QtWidgets.QPushButton(self.tab_queries)
        self.deleteQuery.setObjectName("deleteQuery")
        self.horizontalLayout.addWidget(self.deleteQuery)
        self.newQuery = QtWidgets.QPushButton(self.tab_queries)
        self.newQuery.setObjectName("newQuery")
        self.horizontalLayout.addWidget(self.newQuery)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.queryEdit = QtWidgets.QPlainTextEdit(self.tab_queries)
        self.queryEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.queryEdit.setObjectName("queryEdit")
        self.horizontalLayout_2.addWidget(self.queryEdit)
        self.addQuery = QtWidgets.QPushButton(self.tab_queries)
        self.addQuery.setObjectName("addQuery")
        self.horizontalLayout_2.addWidget(self.addQuery)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.instruction_lbl = QtWidgets.QLabel(self.tab_queries)
        self.instruction_lbl.setText("")
        self.instruction_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_lbl.setObjectName("instruction_lbl")
        self.verticalLayout_2.addWidget(self.instruction_lbl)
        self.tabWidget.addTab(self.tab_queries, "")
        self.tab_references = QtWidgets.QWidget()
        self.tab_references.setObjectName("tab_references")
        self.tabWidget.addTab(self.tab_references, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.error_lbl = QtWidgets.QLabel(expansionWin)
        self.error_lbl.setMinimumSize(QtCore.QSize(0, 20))
        self.error_lbl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.error_lbl.setText("")
        self.error_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.error_lbl.setObjectName("error_lbl")
        self.verticalLayout_3.addWidget(self.error_lbl)
        self.executeQuery = QtWidgets.QPushButton(expansionWin)
        self.executeQuery.setObjectName("executeQuery")
        self.verticalLayout_3.addWidget(self.executeQuery)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(expansionWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(expansionWin)

    def retranslateUi(self, expansionWin):
        _translate = QtCore.QCoreApplication.translate
        expansionWin.setWindowTitle(_translate("expansionWin", "Context Expansion"))
        self.deleteQuery.setText(_translate("expansionWin", "Delete query"))
        self.newQuery.setText(_translate("expansionWin", "New query"))
        self.addQuery.setText(_translate("expansionWin", "Add query"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_queries), _translate("expansionWin", "Expand by Semantic Scholar queries"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_references), _translate("expansionWin", "Expand by paper references"))
        self.executeQuery.setText(_translate("expansionWin", "EXECUTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    expansionWin = QtWidgets.QDialog()
    ui = Ui_expansionWin()
    ui.setupUi(expansionWin)
    expansionWin.show()
    sys.exit(app.exec_())
