# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_filter(object):
    def setupUi(self, new_filter):
        new_filter.setObjectName("new_filter")
        new_filter.resize(400, 168)
        new_filter.setMinimumSize(QtCore.QSize(0, 0))
        new_filter.setMaximumSize(QtCore.QSize(999999, 999999))
        self.verticalLayout = QtWidgets.QVBoxLayout(new_filter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.processName = QtWidgets.QLabel(new_filter)
        self.processName.setObjectName("processName")
        self.horizontalLayout_3.addWidget(self.processName)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.process_name = QtWidgets.QLineEdit(new_filter)
        self.process_name.setObjectName("process_name")
        self.horizontalLayout_3.addWidget(self.process_name)
        self.delete_btn = QtWidgets.QPushButton(new_filter)
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_3.addWidget(self.delete_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.instruction_lbl = QtWidgets.QLabel(new_filter)
        self.instruction_lbl.setMinimumSize(QtCore.QSize(20, 35))
        self.instruction_lbl.setMaximumSize(QtCore.QSize(16777215, 35))
        self.instruction_lbl.setText("")
        self.instruction_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.instruction_lbl.setObjectName("instruction_lbl")
        self.verticalLayout.addWidget(self.instruction_lbl)
        self.filter_edit = QtWidgets.QPlainTextEdit(new_filter)
        self.filter_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filter_edit.setObjectName("filter_edit")
        self.verticalLayout.addWidget(self.filter_edit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.error_lbl = QtWidgets.QLabel(new_filter)
        self.error_lbl.setObjectName("error_lbl")
        self.horizontalLayout_2.addWidget(self.error_lbl)
        self.save_btn = QtWidgets.QPushButton(new_filter)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(new_filter)
        QtCore.QMetaObject.connectSlotsByName(new_filter)

    def retranslateUi(self, new_filter):
        _translate = QtCore.QCoreApplication.translate
        new_filter.setWindowTitle(_translate("new_filter", "New Process"))
        self.processName.setText(_translate("new_filter", "Filter name (optional):"))
        self.process_name.setPlaceholderText(_translate("new_filter", "Type the filter\'s name here..."))
        self.error_lbl.setText(_translate("new_filter", "ERROR LABEL"))
        self.save_btn.setText(_translate("new_filter", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_filter = QtWidgets.QDialog()
    ui = Ui_new_filter()
    ui.setupUi(new_filter)
    new_filter.show()
    sys.exit(app.exec_())
