# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_context_dialog(object):
    def setupUi(self, new_context_dialog):
        new_context_dialog.setObjectName("new_context_dialog")
        new_context_dialog.resize(300, 250)
        new_context_dialog.setMinimumSize(QtCore.QSize(300, 250))
        new_context_dialog.setMaximumSize(QtCore.QSize(300, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(new_context_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.requestTitle = QtWidgets.QLabel(new_context_dialog)
        self.requestTitle.setIndent(3)
        self.requestTitle.setObjectName("requestTitle")
        self.horizontalLayout.addWidget(self.requestTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.new_name = QtWidgets.QLineEdit(new_context_dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.new_name.setFont(font)
        self.new_name.setObjectName("new_name")
        self.horizontalLayout.addWidget(self.new_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(new_context_dialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(3)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.import_from = QtWidgets.QComboBox(new_context_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_from.sizePolicy().hasHeightForWidth())
        self.import_from.setSizePolicy(sizePolicy)
        self.import_from.setMinimumSize(QtCore.QSize(80, 0))
        self.import_from.setObjectName("import_from")
        self.import_from.addItem("")
        self.import_from.addItem("")
        self.horizontalLayout_4.addWidget(self.import_from)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.context_list = QtWidgets.QListWidget(new_context_dialog)
        self.context_list.setObjectName("context_list")
        self.horizontalLayout_3.addWidget(self.context_list)
        self.library_list = QtWidgets.QListWidget(new_context_dialog)
        self.library_list.setObjectName("library_list")
        self.horizontalLayout_3.addWidget(self.library_list)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.error_lbl = QtWidgets.QLabel(new_context_dialog)
        self.error_lbl.setObjectName("error_lbl")
        self.horizontalLayout_2.addWidget(self.error_lbl)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_context_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(new_context_dialog)
        self.buttonBox.accepted.connect(new_context_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(new_context_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_context_dialog)

    def retranslateUi(self, new_context_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_context_dialog.setWindowTitle(_translate("new_context_dialog", "New Context"))
        self.requestTitle.setText(_translate("new_context_dialog", "Context\'s name:"))
        self.new_name.setPlaceholderText(_translate("new_context_dialog", "Context\'s name here..."))
        self.label.setText(_translate("new_context_dialog", "Import from:"))
        self.import_from.setItemText(0, _translate("new_context_dialog", "Libraries"))
        self.import_from.setItemText(1, _translate("new_context_dialog", "Contexts"))
        self.error_lbl.setText(_translate("new_context_dialog", "ERROR LABEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_context_dialog = QtWidgets.QDialog()
    ui = Ui_new_context_dialog()
    ui.setupUi(new_context_dialog)
    new_context_dialog.show()
    sys.exit(app.exec_())
