# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_review_dialog(object):
    def setupUi(self, new_review_dialog):
        new_review_dialog.setObjectName("new_review_dialog")
        new_review_dialog.resize(400, 90)
        new_review_dialog.setMinimumSize(QtCore.QSize(400, 90))
        new_review_dialog.setMaximumSize(QtCore.QSize(400, 90))
        self.verticalLayout = QtWidgets.QVBoxLayout(new_review_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.requestTitle = QtWidgets.QLabel(new_review_dialog)
        self.requestTitle.setObjectName("requestTitle")
        self.horizontalLayout.addWidget(self.requestTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.new_name = QtWidgets.QLineEdit(new_review_dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.new_name.setFont(font)
        self.new_name.setObjectName("new_name")
        self.horizontalLayout.addWidget(self.new_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.error_lbl = QtWidgets.QLabel(new_review_dialog)
        self.error_lbl.setObjectName("error_lbl")
        self.horizontalLayout_2.addWidget(self.error_lbl)
        self.buttonBox = QtWidgets.QDialogButtonBox(new_review_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(new_review_dialog)
        self.buttonBox.accepted.connect(new_review_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(new_review_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(new_review_dialog)

    def retranslateUi(self, new_review_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_review_dialog.setWindowTitle(_translate("new_review_dialog", "New Review"))
        self.requestTitle.setText(_translate("new_review_dialog", "Review\'s name:"))
        self.new_name.setPlaceholderText(_translate("new_review_dialog", "Type a name for the new literature review"))
        self.error_lbl.setText(_translate("new_review_dialog", "ERROR LABEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_review_dialog = QtWidgets.QDialog()
    ui = Ui_new_review_dialog()
    ui.setupUi(new_review_dialog)
    new_review_dialog.show()
    sys.exit(app.exec_())
