#!/usr/bin/env python3
"""Renders docker/nginx.conf and docker/nginx-bootstrap.conf from their
.template counterparts, filling in ${PUBLIC_HOST}/${API_PORT}/
${CONTROLS_FN_HOST}/${CONTROLS_FN_PORT} from the top-level secrets.json --
the same file api/config.py reads everything else from, so the domain/ports
live in exactly one place instead of also being baked into the nginx config
committed to git.

The templates are the tracked files; the rendered .conf files are
gitignored (like secrets.json itself) and regenerated by this script.

Run manually after editing secrets.json or the .template files, before
`docker compose up` (see DEPLOY.md step 10):

    python3 scripts/render_nginx_conf.py
"""
import json
import sys
from pathlib import Path
from string import Template

PROJECT_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = [
    PROJECT_DIR / "docker" / "nginx.conf.template",
    PROJECT_DIR / "docker" / "nginx-bootstrap.conf.template",
]


def load_settings() -> dict:
    secrets_path = PROJECT_DIR / "secrets.json"
    if not secrets_path.exists():
        sys.exit(f"{secrets_path} not found -- copy secrets.json.example and fill it in first.")
    data = json.loads(secrets_path.read_text(encoding="utf-8"))
    settings = {
        "PUBLIC_HOST": data.get("PUBLIC_HOST", ""),
        "API_PORT": data.get("API_PORT", "8000"),
        "CONTROLS_FN_HOST": data.get("CONTROLS_FN_HOST", ""),
        "CONTROLS_FN_PORT": data.get("CONTROLS_FN_PORT", ""),
    }
    missing = [k for k, v in settings.items() if not str(v).strip()]
    if missing:
        sys.exit(f"secrets.json is missing a value for: {', '.join(missing)}")
    return settings


def render(template_path: Path, settings: dict) -> Path:
    """safe_substitute (not substitute) -- the templates are also full of
    nginx's own $host/$request_uri/$remote_addr/... variables, which must
    pass through untouched rather than raising as unknown template keys."""
    out_path = template_path.with_suffix("")  # drop the trailing ".template"
    rendered = Template(template_path.read_text(encoding="utf-8")).safe_substitute(settings)
    out_path.write_text(rendered, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    settings = load_settings()
    for template_path in TEMPLATES:
        out_path = render(template_path, settings)
        print(f"wrote {out_path.relative_to(PROJECT_DIR)}")
